spring:
  jpa:
    # 전송 쿼리 확인
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # 테이블 생성 후에 data.sql 실행
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client-id
            client-secret: client-secret
            scope:
              - email
              - profile

jwt:
  issuer: dbswjd4991@gmail.com
  secret_key: secret-key